# Generated by Django 2.0.2 on 2018-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0002_auto_20180222_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='products', to='zerShop.Category'),
        ),
    ]
