# Generated by Django 2.0.2 on 2018-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0003_auto_20180223_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
