# Generated by Django 2.0.2 on 2018-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0006_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
