# Generated by Django 2.0.2 on 2018-03-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0009_auto_20180301_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
