# Generated by Django 2.0.2 on 2018-03-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0010_auto_20180301_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Черный'), ('gray', 'Серый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('red', 'Красный'), ('blue', 'Синий')], default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price_discounted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
