# Generated by Django 2.0.2 on 2018-03-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerShop', '0020_auto_20180302_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
