# Generated by Django 2.0.2 on 2018-03-06 13:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zerShop', '0022_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата добавления отзыва')),
                ('status', models.BooleanField(default=False, verbose_name='Показывать отзыв')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='5', verbose_name='Рейтинг товара')),
                ('product', models.ForeignKey(on_delete='CASCADE', related_name='products', to='zerShop.Product')),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
